###FROM openjdk:8-jdk-alpine
FROM adoptopenjdk/openjdk11:alpine

RUN apk --no-cache add curl

#RUN addgroup -S spring && adduser -S spring -G spring
#USER spring:spring

VOLUME /tmp

ARG REGION_ARG=sa-east-1
ARG AWS_ACCESS_ARG
ARG AWS_SECRET_ARG
ARG PROFILES_ACTIVE_ARG
ARG MONGODB_USERNAME_ARG
ARG MONGODB_PASSWORD_ARG
ARG MONGODB_HOST_ARG

ENV AWS_REGION=$REGION_ARG
ENV AWS_ACCESS_KEY=$AWS_ACCESS_ARG
ENV AWS_SECRET_KEY=$AWS_SECRET_ARG
ENV SPRING_PROFILES_ACTIVE=$PROFILES_ACTIVE_ARG
ENV NIKODAY_MONGODB_USERNAME=$MONGODB_USERNAME_ARG
ENV NIKODAY_MONGODB_PASSWORD=$MONGODB_PASSWORD_ARG
ENV NIKODAY_MONGODB_HOST=$MONGODB_HOST_ARG


ARG JAR_FILE=target/*.jar

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", "-jar", "/app.jar"]
