server:
  port: 8080
  servlet:
    context-path: /api
spring:
  profiles:
    active: sandbox
  data:
    mongodb:
      uri: mongodb+srv://${NIKODAY_MONGODB_USERNAME}:${NIKODAY_MONGODB_PASSWORD}@${NIKODAY_MONGODB_HOST}/nikoday-sandbox?retryWrites=true&w=majority
      auto-index-creation: false
logging:
  level:
    root: INFO
    org.apache: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.mongodb: INFO
    org.frekele.nikoday: DEBUG